import { Container, Paper, Typography } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles({
  main: {
    marginTop:34
  }
});

const Home = () => {
  const classes = useStyles();
  return (
    <Container className={classes.main}>
        <br/>
        <Paper>
            <Typography>Home page

            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna molestie at elementum eu facilisis. Sem integer vitae justo eget magna fermentum iaculis. Viverra tellus in hac habitasse. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Integer feugiat scelerisque varius morbi enim nunc faucibus. Duis at consectetur lorem donec massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum vitae sapien pellentesque habitant. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Sit amet mattis vulputate enim nulla. Eu augue ut lectus arcu bibendum at. Semper auctor neque vitae tempus. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas purus viverra accumsan in. Aliquam nulla facilisi cras fermentum.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna molestie at elementum eu facilisis. Sem integer vitae justo eget magna fermentum iaculis. Viverra tellus in hac habitasse. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Integer feugiat scelerisque varius morbi enim nunc faucibus. Duis at consectetur lorem donec massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum vitae sapien pellentesque habitant. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Sit amet mattis vulputate enim nulla. Eu augue ut lectus arcu bibendum at. Semper auctor neque vitae tempus. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas purus viverra accumsan in. Aliquam nulla facilisi cras fermentum.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna molestie at elementum eu facilisis. Sem integer vitae justo eget magna fermentum iaculis. Viverra tellus in hac habitasse. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Integer feugiat scelerisque varius morbi enim nunc faucibus. Duis at consectetur lorem donec massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum vitae sapien pellentesque habitant. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Sit amet mattis vulputate enim nulla. Eu augue ut lectus arcu bibendum at. Semper auctor neque vitae tempus. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas purus viverra accumsan in. Aliquam nulla facilisi cras fermentum.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna molestie at elementum eu facilisis. Sem integer vitae justo eget magna fermentum iaculis. Viverra tellus in hac habitasse. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Integer feugiat scelerisque varius morbi enim nunc faucibus. Duis at consectetur lorem donec massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum vitae sapien pellentesque habitant. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Sit amet mattis vulputate enim nulla. Eu augue ut lectus arcu bibendum at. Semper auctor neque vitae tempus. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas purus viverra accumsan in. Aliquam nulla facilisi cras fermentum.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna molestie at elementum eu facilisis. Sem integer vitae justo eget magna fermentum iaculis. Viverra tellus in hac habitasse. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Integer feugiat scelerisque varius morbi enim nunc faucibus. Duis at consectetur lorem donec massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum vitae sapien pellentesque habitant. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Sit amet mattis vulputate enim nulla. Eu augue ut lectus arcu bibendum at. Semper auctor neque vitae tempus. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas purus viverra accumsan in. Aliquam nulla facilisi cras fermentum.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Urna molestie at elementum eu facilisis. Sem integer vitae justo eget magna fermentum iaculis. Viverra tellus in hac habitasse. Consequat interdum varius sit amet mattis vulputate enim nulla aliquet. Integer feugiat scelerisque varius morbi enim nunc faucibus. Duis at consectetur lorem donec massa. Vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Condimentum vitae sapien pellentesque habitant. Tellus at urna condimentum mattis pellentesque id nibh tortor id. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Sit amet mattis vulputate enim nulla. Eu augue ut lectus arcu bibendum at. Semper auctor neque vitae tempus. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Egestas purus viverra accumsan in. Aliquam nulla facilisi cras fermentum.
            </Typography>
        </Paper>
    </Container>
  );
};

export default Home;